### ISSUE TITLE
🚨 CBOR name collision with Apple private CBORLibrary.framework type

### ISSUE THREAD

**Issue by phatblat** [getditto/TinyCborObjc#24]
[CBOR](https://github.com/getditto/TinyCborObjc/blob/master/ObjCCBOR/CBOR.h#L13) has the same type as an Objective-C class defined in a private Apple framework:

> objc[95218]: Class CBOR is implemented in both /System/Library/PrivateFrameworks/CBORLibrary.framework/Versions/A/CBORLibrary (0x25064ffc8) and /private/var/folders/c9/lynprlfx2vd6zjj5m37_54d80000gn/X/4E9FC690-9374-5E25-B39B-FDEED4BA48DA/d/Wrapper/SP Flex.app/Frameworks/DittoObjC.framework/DittoObjC (0x10e94caf8). One of the two will be used. Which one is undefined.

This type should be renamed (convention is a 3-letter prefix for the company or library) so that it doesn't collide with Apple's type.

**Comment by hamchapman** [comment]
Yeah if we're not going to try and bring the upstream along with us (which would take some extra effort on our part and I'm not sure it's worth it for us, or generally) then the renaming and prefixing plan sounds good to me 👍
